# 模型参数
model_name_or_path: ./models/Qwen/Qwen2.5-3B-Instruct/
model_revision: main
# torch_dtype: bfloat16
# 由于我这里使用的是Turing架构的卡，不支持 bf16，因此使用 fp16
torch_dtype: float16
# 这里注掉的原因是我的卡比较老，不支持 flash-attn
# attn_implementation: flash_attention_2
# 由于我这里使用的是Turing架构的卡，不支持 bf16 和 tf32
bf16: false
tf32: false
output_dir: output/deepseek-R1-reproduce

# 数据集参数
dataset_id_or_path: ./dataset

# Swanlab 训练流程记录参数
swanlab: false # 是否开启 Swanlab 
workspace: oehuosi
project: deepseek-R1-reproduce_by_ohuo
experiment_name: qwen2.5-3B-lr:5e-7_beta:0.001

# 训练参数
max_steps: 450 # 最大训练步长
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7 # 学习率
lr_scheduler_type: cosine # 学习率衰减方案
warmup_ratio: 0.03 # 学习率预热比率（对于整个步长）
seed: 2025 # 随机种子，方便实验复现

# GRPO 算法参数
beta: 0.001 # KL 惩罚因子
max_prompt_length: 256 # 输入 prompt 最大长度
max_completion_length: 512 # 输出回答长度，包含推理思维链，设为 4K 比较合适
num_generations: 4
use_vllm: true # 启用 vllm 来加速推理
vllm_device: cuda:1 # 留出一张卡来启用 vllm 推理
vllm_gpu_memory_utilization: 0.5

# Logging arguments
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_steps: 50 # 每隔多少步保存一次
